config/routes.rb
Portfolio::Application.routes.draw do

  resources :post_attachments

  namespace :api do
    namespace :v1 do
      resources :posts, :only => [ :create ]
    end
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}


  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resource :comments

  resources :messages

  resources :images

  get 'welcome/index'

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true

  validates_presence_of :author, :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def index
    @comments = Comment.all
  end

  def new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      redirect_to @commentable, notice: "Comment is awaiting moderation"
      CommentMailer.delay_for(2.minutes).new_comment(@comment, @commentable)
    else
      instance_variable_set(("@#{@resource.singularize}").to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    if @comment.save
      redirect_to request.referrer, notice: "Comment edited successfully"
    else
      redirect_to request.referrer, notice: "There was an error with that action"
    end
  end

private

  def comment_params
    params.require(:comment).permit(:author, :author_email, :author_url, :content)
  end

  def load_commentable
    @resource, id =request.path.split('/')[1,2]
    @commentable = @resource.singularize.classify.constantize.find(id)
  end
end

app/views/comments/_form.html.erb
<div class="comment_form">
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.present? %>
    <%= form_for [@commentable, @comment] do |f| %>
      <div class="field">
        <%= f.label :author, "Name" %>
        <%= f.text_field :author %>
      </div>
      <div class="field">
        <%= f.label :author_email, "Email" %>
        <%= f.text_field :author_email %>
      </div>
      <div class="field">
        <%= f.label :author_url, "Website" %>
        <%= f.text_field :author_url %>
      </div>
      <div class="field">
        <%= f.label :content, "Comment" %>
        <%= f.text_field :content %>
      </div>
      <div class="actions">
        <%= f.submit "Submit comment" %>
      <div>
    <% end %>
  <% else %>
    <div>
      <%= link_to("You must sign in to comment", new_user_session_path) %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<h1>Approve comments</h1>
<% @comments.each do |comment| %>
  <%= comment.content %>
  <%= link_to 'Edit', edit_comments_path(comment), class: "btn btn-info" %>
  <% if comment.approved? %>
    <h2> Comment approved by post author %>
  <% else %>
     <%= button_to 'Approve', post_comment_path(@commentable, comment, comment: {approved: true}), method: :put, class: 'comment_approve'%>
  <% end %>
<% end %>