config/routes.rb
Portfolio::Application.routes.draw do

  resources :post_attachments

  namespace :api do
    namespace :v1 do
      resources :posts, :only => [ :create ]
    end
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}


  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  resource :comments

  resources :messages

  resources :images

  get 'welcome/index'

  root 'posts#index'
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Thomas Osborn</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="underline">
  <div id="topbar">
    <ul>
      <li><%= link_to "About", welcome_index_path %></li>
      <li><%= link_to "Blog", posts_path %></li>
      <li><%= link_to "Portfolio", projects_path %></li>
      <li><%= link_to "Contact", new_message_path %></li>
    </ul>
  </div>
</div>
<div id="namebar">
  <%= image_tag('portfolio-banner.jpg') %>
</div>
<div id="thinline">
  <div id="topbar">
    <ul>
      <li><a href="http://www.github.com/trosborn">Github</a></li>
      <li><a href="http://www.twitter.com/joosushi">Twitter</a></li>
      <li><a href="http://www.linkedin.com/in/trosborn/en">Linkedin</a></li>
    </ul>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="row">
    <div class="large-12 columns">
      <div data-alert class="alert-box <%= flash_class(key) %>">
        <%= value %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Thomas Osborn | Web Developer" %></title>
    <%= favicon_link_tag 'sto.ico' %>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="row">
      <div class="large-12 columns">
        <%= render "layouts/header" %>
        </br>
        <%= render "layouts/messages" %>
        <%= yield %>
        <%= render "layouts/footer" %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
  </body>
</html>